// Data pools for the synthetic test mail. Everything here is invented: addresses use only
// reserved domains (RFC 2606 / RFC 6761: .test, .example, .invalid, example.com/net/org) —
// never a real address or domain (this repo is public). All strings are NFC; together they
// cover every Slovak diacritic letter (á ä č ď é í ľ ĺ ň ó ô ŕ š ť ú ý ž).
// Changing anything here changes the generated bytes: bump SEED_VERSION (see generator.ts).

export const SENDERS: readonly { name: string; address: string }[] = [
  { name: 'Ľubica Ďurišová', address: 'lubica.durisova@example.com' },
  { name: 'Peter Novák', address: 'peter.novak@example.org' },
  { name: 'Ján Ôsmy', address: 'jan.osmy@example.org' },
  { name: 'Žofia Čierna', address: 'zofia.cierna@example.com' },
  { name: 'Obchod Čučoriedka', address: 'info@obchod.example' },
  { name: 'Obchod Čučoriedka – objednávky', address: 'objednavky@obchod.example' },
  { name: 'Banka Šťastie', address: 'podpora@banka.example' },
  { name: 'Energia Päť', address: 'faktury@energia.example' },
  { name: 'Škola Ťahanovce', address: 'ucitel@skola.test' },
  { name: 'Novinky z mesta', address: 'redakcia@novinky.example' },
  { name: 'Notifikácie účtu', address: 'noreply@notifikacie.example.net' },
  { name: 'Výhra Dnes', address: 'vyhra@spam.test' },
  { name: 'Akciové ponuky', address: 'akcie@spam.test' },
  { name: 'Lacné pôžičky', address: 'pozicky@spam.test' },
  { name: 'Banka Šťastie (bezpečnosť)', address: 'promo@spam.test.evil.test' },
  { name: 'Kĺbová výživa', address: 'zdravie@spam.test.evil.test' },
];

/** `{n}` = a number, `{year}` = the message's year. */
export const SUBJECT_TEMPLATES: readonly string[] = [
  'Faktúra č. {n}/{year}',
  'Výpis z účtu za {year}',
  'Ďakujeme za objednávku č. {n}',
  'Pozvánka na stretnutie v piatok',
  'Re: Otázka k zmluve č. {n}',
  'Fwd: Fotky z výletu',
  'Ahoj, ako sa máš?',
  'Zľava 50 % len dnes!',
  'Gratulujeme, vyhrali ste!',
  'Vaša zásielka č. {n} je pripravená',
  '📦 Zásielka je na ceste',
  'Pripomienka: termín platby {n}. {year}',
  'Téma na víkend: mäso na grile',
  'Žiadosť o doplnenie údajov',
  'Rozpis služieb na ôsmy týždeň',
  'Nový rozvrh hodín – {year}',
  'Posledná šanca: pôžička bez poplatkov',
  'Oznam o výpadku vody a móde parkovania',
  'Potvrdenie platby č. {n}',
  'Stretnutie triedy po {n} rokoch',
  'Vŕba pri potoku – fotky',
  'Zmena hesla k účtu',
  'Kĺbová výživa za polovicu',
  'Pozdrav z Ďumbiera',
  'Ročné vyúčtovanie energií {year}',
];

export const BODY_SENTENCES: readonly string[] = [
  'Dobrý deň, posielam Vám sľúbené podklady.',
  'Ďakujem za rýchlu odpoveď a prajem pekný deň.',
  'V prílohe nájdete faktúru za minulý mesiac.',
  'Stretneme sa v piatok o piatej pri vŕbe.',
  'Nezabudnite si priniesť občiansky preukaz.',
  'Mäso na grile bude hotové o pol hodiny.',
  'Ôsmy ročník podujatia začína už v sobotu.',
  'Kĺb ma stále bolí, tak zostanem doma.',
  'Päť minút pred koncom sa ozval ďalší zákazník.',
  'Žiadosť sme prijali a spracujeme ju do troch dní.',
  'S ňou sme sa dohodli na novom termíne.',
  'Téma tohto týždňa je šetrenie energiou.',
  'Víkend strávime na chate pri jazere.',
  'Ľutujeme, ale objednaný tovar je vypredaný.',
  'Ťahanovce majú nový park s ihriskom.',
  'Účet bol úspešne aktualizovaný.',
  'Výsledky súťaže zverejníme budúci týždeň.',
  'Čaká na Vás darček, stačí kliknúť.',
  'Ďalšie informácie Vám pošleme e-mailom.',
  'Srdečne pozdravujem celú rodinu.',
];

/** `{n}` = a number, `{year}` = the message's year. The extension picks the content type. */
export const ATTACHMENT_NAME_TEMPLATES: readonly string[] = [
  'Výpis účtu {year}.bin',
  'Zmluva – návrh {n}.txt',
  'Rozpočet {year}.csv',
  'Fotky z výletu {n}.bin',
  'Faktúra č. {n}.bin',
  'Poznámky zo stretnutia {n}.txt',
  'Vyúčtovanie energií {year}.csv',
  'Záloha dokumentov {n}.bin',
  'Ôsmy týždeň – rozpis.txt',
  'Kĺbová výživa – cenník.csv',
];
